/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYPDF_ONE_MINUS_SQUARED
#define MYPDF_ONE_MINUS_SQUARED

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyPdf_one_minus_squared : public RooAbsPdf {
public:
  MyPdf_one_minus_squared() {} ; 
  MyPdf_one_minus_squared(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _c0);
  MyPdf_one_minus_squared(const MyPdf_one_minus_squared& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyPdf_one_minus_squared(*this,newname); }
  inline virtual ~MyPdf_one_minus_squared() { }

protected:

  RooRealProxy x ;
  RooRealProxy c0 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyPdf_one_minus_squared,1) // Your description goes here...
};
 
#endif
