/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYPDF_XSQUARED
#define MYPDF_XSQUARED

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyPdf_xsquared : public RooAbsPdf {
public:
  MyPdf_xsquared() {} ; 
  MyPdf_xsquared(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _c0);
  MyPdf_xsquared(const MyPdf_xsquared& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyPdf_xsquared(*this,newname); }
  inline virtual ~MyPdf_xsquared() { }

protected:

  RooRealProxy x ;
  RooRealProxy c0 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyPdf_xsquared,1) // Your description goes here...
};
 
#endif
