/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "MyPdf_x**2.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(MyPdf_x**2); 

 MyPdf_x**2::MyPdf_x**2(const char *name, const char *title, 
                        RooAbsReal& _x) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x)
 { 
 } 


 MyPdf_x**2::MyPdf_x**2(const MyPdf_x**2& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x)
 { 
 } 



 Double_t MyPdf_x**2::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return x*x ; 
 } 



