/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYPDF_XSQUARED_NOPARA
#define MYPDF_XSQUARED_NOPARA

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyPdf_xsquared_nopara : public RooAbsPdf {
public:
  MyPdf_xsquared_nopara() {} ; 
  MyPdf_xsquared_nopara(const char *name, const char *title,
	      RooAbsReal& _x);
  MyPdf_xsquared_nopara(const MyPdf_xsquared_nopara& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyPdf_xsquared_nopara(*this,newname); }
  inline virtual ~MyPdf_xsquared_nopara() { }

protected:

  RooRealProxy x ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyPdf_xsquared_nopara,1) // Your description goes here...
};
 
#endif
