/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "MyPdf_one_minus_squared.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(MyPdf_one_minus_squared); 

 MyPdf_one_minus_squared::MyPdf_one_minus_squared(const char *name, const char *title, 
                        RooAbsReal& _y) :
   RooAbsPdf(name,title), 
   y("y","y",this,_y)
 { 
 } 


 MyPdf_one_minus_squared::MyPdf_one_minus_squared(const MyPdf_one_minus_squared& other, const char* name) :  
   RooAbsPdf(other,name), 
   y("y",this,other.y)
 { 
 } 



 Double_t MyPdf_one_minus_squared::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1-y*y ; 
 } 



