/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "MyPdf_one_minus_squared.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(MyPdf_one_minus_squared); 

 MyPdf_one_minus_squared::MyPdf_one_minus_squared(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _c0) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   c0("c0","c0",this,_c0)
 { 
 } 


 MyPdf_one_minus_squared::MyPdf_one_minus_squared(const MyPdf_one_minus_squared& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   c0("c0",this,other.c0)
 { 
 } 



 Double_t MyPdf_one_minus_squared::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return c0*(1-x*x) ; 
 } 



